source("./main.R")

dnaStr1 <- "AGCTTTTCATTCTGACTGCAACGGGCAATATGTCTCTGTGTGGATTAAAAAAAGAGTGTCTGATAGCAGC"
countNucleotides(dnaStr1)

dnaStr2 <- "GATGGAACTTGACTACGTAAATT"
dnaToRna(dnaStr2)

dnaStr3 <- "AAAACCCGGT"
reverseComplement(dnaStr3)

dnaStr4 <- "CCACCCTCGTGGTATGGCTAGGCATTCAGGAACCGGAGAACGCTTCAGACCAGCCCGGACTGGGAACCTGCGGGCAGTAGGTGGAAT"
gcContent(dnaStr4)

dnaStr5 <- "GAGCCTACTAACGGGAT"
dnaStr6 <- "CATCGTAATGACGGCCT"
countPointMutations(dnaStr5, dnaStr6)

rnaStr <- "AUGGCCAUGGCGCCCAGAACUGAGAUCAAUAGUACCCGUAUUAACGGGUGA"
rnaToProtein(rnaStr)
